//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fltstd26.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fltstd26.Resources.Texts.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortfahren ähnelt.
        /// </summary>
        internal static string assistant_continue {
            get {
                return ResourceManager.GetString("assistant_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tauschen ähnelt.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfernen ähnelt.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Markieren ähnelt.
        /// </summary>
        internal static string flag {
            get {
                return ResourceManager.GetString("flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abflugtafel einrichten ähnelt.
        /// </summary>
        internal static string iaboard {
            get {
                return ResourceManager.GetString("iaboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spalte Hinzufügen ähnelt.
        /// </summary>
        internal static string iaboard_add {
            get {
                return ResourceManager.GetString("iaboard_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenquelle ähnelt.
        /// </summary>
        internal static string iaboard_binding {
            get {
                return ResourceManager.GetString("iaboard_binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string iaboard_name {
            get {
                return ResourceManager.GetString("iaboard_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sichtbarkeit ähnelt.
        /// </summary>
        internal static string iaboard_visibility {
            get {
                return ResourceManager.GetString("iaboard_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breite ähnelt.
        /// </summary>
        internal static string iaboard_width {
            get {
                return ResourceManager.GetString("iaboard_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informationen ähnelt.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        internal static string menubar_file {
            get {
                return ResourceManager.GetString("menubar_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        internal static string menubar_help {
            get {
                return ResourceManager.GetString("menubar_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwalten ähnelt.
        /// </summary>
        internal static string menubar_manage {
            get {
                return ResourceManager.GetString("menubar_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        internal static string menubar_system {
            get {
                return ResourceManager.GetString("menubar_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        /// </summary>
        internal static string menubar_view {
            get {
                return ResourceManager.GetString("menubar_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigen ähnelt.
        /// </summary>
        internal static string notify {
            get {
                return ResourceManager.GetString("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einfügen ähnelt.
        /// </summary>
        internal static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederholen ähnelt.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginnen ähnelt.
        /// </summary>
        internal static string startButton {
            get {
                return ResourceManager.GetString("startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückgängig ähnelt.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen im Flugplaner Studio 2026! ähnelt.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        internal static string xplan_add {
            get {
                return ResourceManager.GetString("xplan_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string xplan_auto {
            get {
                return ResourceManager.GetString("xplan_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anlegen ähnelt.
        /// </summary>
        internal static string xplan_creator {
            get {
                return ResourceManager.GetString("xplan_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        /// </summary>
        internal static string xplan_length {
            get {
                return ResourceManager.GetString("xplan_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung ähnelt.
        /// </summary>
        internal static string xplan_name {
            get {
                return ResourceManager.GetString("xplan_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fixiert ähnelt.
        /// </summary>
        internal static string xplan_persistent {
            get {
                return ResourceManager.GetString("xplan_persistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preis in Eurocent ähnelt.
        /// </summary>
        internal static string xplan_price {
            get {
                return ResourceManager.GetString("xplan_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A.S.A.P. ähnelt.
        /// </summary>
        internal static string xplan_quickticket {
            get {
                return ResourceManager.GetString("xplan_quickticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luftfahrzeug wählen ähnelt.
        /// </summary>
        internal static string xplan_select_lfz {
            get {
                return ResourceManager.GetString("xplan_select_lfz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterwegs ähnelt.
        /// </summary>
        internal static string xplan_status_airborne {
            get {
                return ResourceManager.GetString("xplan_status_airborne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anflug ähnelt.
        /// </summary>
        internal static string xplan_status_app {
            get {
                return ResourceManager.GetString("xplan_status_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgesagt ähnelt.
        /// </summary>
        internal static string xplan_status_cancel {
            get {
                return ResourceManager.GetString("xplan_status_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verzögert ähnelt.
        /// </summary>
        internal static string xplan_status_delayed {
            get {
                return ResourceManager.GetString("xplan_status_delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abflug ähnelt.
        /// </summary>
        internal static string xplan_status_dpt {
            get {
                return ResourceManager.GetString("xplan_status_dpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgeschlossen ähnelt.
        /// </summary>
        internal static string xplan_status_finished {
            get {
                return ResourceManager.GetString("xplan_status_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tankflug ähnelt.
        /// </summary>
        internal static string xplan_status_fuel {
            get {
                return ResourceManager.GetString("xplan_status_fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Planmäßig ähnelt.
        /// </summary>
        internal static string xplan_status_ontime {
            get {
                return ResourceManager.GetString("xplan_status_ontime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Außer Betrieb ähnelt.
        /// </summary>
        internal static string xplan_status_outofservice {
            get {
                return ResourceManager.GetString("xplan_status_outofservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereit ähnelt.
        /// </summary>
        internal static string xplan_status_ready {
            get {
                return ResourceManager.GetString("xplan_status_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht Verfügbar ähnelt.
        /// </summary>
        internal static string xplan_status_unavail {
            get {
                return ResourceManager.GetString("xplan_status_unavail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unklar ähnelt.
        /// </summary>
        internal static string xplan_status_unclear {
            get {
                return ResourceManager.GetString("xplan_status_unclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warten ähnelt.
        /// </summary>
        internal static string xplan_status_waiting {
            get {
                return ResourceManager.GetString("xplan_status_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gewicht ähnelt.
        /// </summary>
        internal static string xplan_weight {
            get {
                return ResourceManager.GetString("xplan_weight", resourceCulture);
            }
        }
    }
}
