//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fltstd26.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fltstd26.Resources.Texts.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XFly Management Studio ist ein System, um den Gastflugverkehr an kleinen Flugplätzen einfach zu regeln. Es hilft durch Visualisierung sowohl den Gästen als auch dem Veranstalter den Überblick über viele Tickets zu haben und die Kasse zu verwalten. 
        ///Dieses Programm basiert auf einer Entwicklung für den Aero Club Bad Nauheim.
        ///© REDFOXX STUDIO ähnelt.
        /// </summary>
        internal static string about_text {
            get {
                return ResourceManager.GetString("about_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luftfahrzeug Konfiguration ähnelt.
        /// </summary>
        internal static string accustomizer {
            get {
                return ResourceManager.GetString("accustomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktivitätsfenster ähnelt.
        /// </summary>
        internal static string activity_range {
            get {
                return ResourceManager.GetString("activity_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lfz. Erstellen ähnelt.
        /// </summary>
        internal static string aircraft_create {
            get {
                return ResourceManager.GetString("aircraft_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwenden ähnelt.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortfahren ähnelt.
        /// </summary>
        internal static string assistant_continue {
            get {
                return ResourceManager.GetString("assistant_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatische Ticket Zuweisung ähnelt.
        /// </summary>
        internal static string autoassign {
            get {
                return ResourceManager.GetString("autoassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verfügbar am: ähnelt.
        /// </summary>
        internal static string available_in_doubledot {
            get {
                return ResourceManager.GetString("available_in_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        internal static string backward {
            get {
                return ResourceManager.GetString("backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luftfahrzeug ähnelt.
        /// </summary>
        internal static string builder_selectLfz {
            get {
                return ResourceManager.GetString("builder_selectLfz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slot ähnelt.
        /// </summary>
        internal static string builder_selectSlot {
            get {
                return ResourceManager.GetString("builder_selectSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte begeben Sie sich jetzt zum Rundflugschalter: ähnelt.
        /// </summary>
        internal static string call_target {
            get {
                return ResourceManager.GetString("call_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank prüfen ähnelt.
        /// </summary>
        internal static string check_db {
            get {
                return ResourceManager.GetString("check_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereinigen ähnelt.
        /// </summary>
        internal static string cleanup {
            get {
                return ResourceManager.GetString("cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank löschen ähnelt.
        /// </summary>
        internal static string clear_db {
            get {
                return ResourceManager.GetString("clear_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uhr Neustart ähnelt.
        /// </summary>
        internal static string clock_restart {
            get {
                return ResourceManager.GetString("clock_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufgabenplanung ähnelt.
        /// </summary>
        internal static string clockcheck {
            get {
                return ResourceManager.GetString("clockcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfigurationseditor öffnen... ähnelt.
        /// </summary>
        internal static string config_editor {
            get {
                return ResourceManager.GetString("config_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfigurationsverzeichnis ähnelt.
        /// </summary>
        internal static string config_manager {
            get {
                return ResourceManager.GetString("config_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen oder erstellen Sie eine Konfiguration: ähnelt.
        /// </summary>
        internal static string config_select {
            get {
                return ResourceManager.GetString("config_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfigurationswechsel ähnelt.
        /// </summary>
        internal static string config_switch {
            get {
                return ResourceManager.GetString("config_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll in die ausgewählte Konfiguration gewechselt werden? ähnelt.
        /// </summary>
        internal static string config_switch_warn {
            get {
                return ResourceManager.GetString("config_switch_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigen ähnelt.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konsole ähnelt.
        /// </summary>
        internal static string console {
            get {
                return ResourceManager.GetString("console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tauschen ähnelt.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschädigte Verknüpfung ähnelt.
        /// </summary>
        internal static string corrupted_links {
            get {
                return ResourceManager.GetString("corrupted_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzerdefiniert ähnelt.
        /// </summary>
        internal static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank ähnelt.
        /// </summary>
        internal static string db {
            get {
                return ResourceManager.GetString("db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Vorgang wird die gesamte Datenbank leeren und ist nicht mehr rückgängig zu machen.
        ///SIND SIE SICHER? ähnelt.
        /// </summary>
        internal static string db_clear_warning {
            get {
                return ResourceManager.GetString("db_clear_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbankvorschau ähnelt.
        /// </summary>
        internal static string db_preview {
            get {
                return ResourceManager.GetString("db_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verspätung ähnelt.
        /// </summary>
        internal static string delay {
            get {
                return ResourceManager.GetString("delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Verzögerung kann in diesem Slot aufgefangen werden ähnelt.
        /// </summary>
        internal static string delay_compensation {
            get {
                return ResourceManager.GetString("delay_compensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Verzögerung kann nicht angewandt werden, da entweder keine Slots mehr verfügbar sind oder die Verzögerung über der höchstmöglichen Beschränkung liegt ähnelt.
        /// </summary>
        internal static string delay_error {
            get {
                return ResourceManager.GetString("delay_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfernen ähnelt.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll der Block wirklich endgültig aus der Datenbank entfernt werden? ähnelt.
        /// </summary>
        internal static string delete_warning {
            get {
                return ResourceManager.GetString("delete_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht berücksichtigen ähnelt.
        /// </summary>
        internal static string dont_care {
            get {
                return ResourceManager.GetString("dont_care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende ähnelt.
        /// </summary>
        internal static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgeführt am:  ähnelt.
        /// </summary>
        internal static string execution_at {
            get {
                return ResourceManager.GetString("execution_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Ausführung am:  ähnelt.
        /// </summary>
        internal static string execution_last {
            get {
                return ResourceManager.GetString("execution_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In File-Explorer öffnen ähnelt.
        /// </summary>
        internal static string explorer_continue {
            get {
                return ResourceManager.GetString("explorer_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Markieren ähnelt.
        /// </summary>
        internal static string flag {
            get {
                return ResourceManager.GetString("flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Planungsintervall: ähnelt.
        /// </summary>
        internal static string flight_interval_doubledot {
            get {
                return ResourceManager.GetString("flight_interval_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flug Optionen ähnelt.
        /// </summary>
        internal static string flight_option {
            get {
                return ResourceManager.GetString("flight_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fluganzahl ähnelt.
        /// </summary>
        internal static string flight_sum {
            get {
                return ResourceManager.GetString("flight_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flüge ähnelt.
        /// </summary>
        internal static string flights {
            get {
                return ResourceManager.GetString("flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Flug ist überbesetzt. Löschen Sie mindestens ein Ticket oder verschieben Sie es aus dem Flug hinaus ähnelt.
        /// </summary>
        internal static string flt_overflow {
            get {
                return ResourceManager.GetString("flt_overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flug ID ähnelt.
        /// </summary>
        internal static string fltno {
            get {
                return ResourceManager.GetString("fltno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        internal static string forward {
            get {
                return ResourceManager.GetString("forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vollständig ähnelt.
        /// </summary>
        internal static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abflugtafel einrichten ähnelt.
        /// </summary>
        internal static string iaboard {
            get {
                return ResourceManager.GetString("iaboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spalte Hinzufügen ähnelt.
        /// </summary>
        internal static string iaboard_add {
            get {
                return ResourceManager.GetString("iaboard_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenquelle ähnelt.
        /// </summary>
        internal static string iaboard_binding {
            get {
                return ResourceManager.GetString("iaboard_binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string iaboard_name {
            get {
                return ResourceManager.GetString("iaboard_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sichtbarkeit ähnelt.
        /// </summary>
        internal static string iaboard_visibility {
            get {
                return ResourceManager.GetString("iaboard_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breite ähnelt.
        /// </summary>
        internal static string iaboard_width {
            get {
                return ResourceManager.GetString("iaboard_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informationen ähnelt.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intervall ähnelt.
        /// </summary>
        internal static string interval {
            get {
                return ResourceManager.GetString("interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Änderung ähnelt.
        /// </summary>
        internal static string last_change {
            get {
                return ResourceManager.GetString("last_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Länge (min): ähnelt.
        /// </summary>
        internal static string length_doubledot {
            get {
                return ResourceManager.GetString("length_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtzeit in der Luft ähnelt.
        /// </summary>
        internal static string length_sum {
            get {
                return ResourceManager.GetString("length_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luftfahrzeuge ähnelt.
        /// </summary>
        internal static string lfz {
            get {
                return ResourceManager.GetString("lfz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kennzeichen ähnelt.
        /// </summary>
        internal static string lfzreg {
            get {
                return ResourceManager.GetString("lfzreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lfz Kennzeichen: ähnelt.
        /// </summary>
        internal static string lfzreg_doubledot {
            get {
                return ResourceManager.GetString("lfzreg_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verknüpfung ähnelt.
        /// </summary>
        internal static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen werden nur bei Drücken von &quot;Aktualisieren&quot; dargestellt! ähnelt.
        /// </summary>
        internal static string manual_refresh {
            get {
                return ResourceManager.GetString("manual_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        internal static string menubar_file {
            get {
                return ResourceManager.GetString("menubar_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cache Ordner öffnen... ähnelt.
        /// </summary>
        internal static string menubar_file_cachefolder {
            get {
                return ResourceManager.GetString("menubar_file_cachefolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfiguration ähnelt.
        /// </summary>
        internal static string menubar_file_config {
            get {
                return ResourceManager.GetString("menubar_file_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten Ordner öffnen... ähnelt.
        /// </summary>
        internal static string menubar_file_datafolder {
            get {
                return ResourceManager.GetString("menubar_file_datafolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateisystem ähnelt.
        /// </summary>
        internal static string menubar_file_filesystem {
            get {
                return ResourceManager.GetString("menubar_file_filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        internal static string menubar_file_profiles {
            get {
                return ResourceManager.GetString("menubar_file_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        internal static string menubar_help {
            get {
                return ResourceManager.GetString("menubar_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwalten ähnelt.
        /// </summary>
        internal static string menubar_manage {
            get {
                return ResourceManager.GetString("menubar_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Netzwerk ähnelt.
        /// </summary>
        internal static string menubar_network {
            get {
                return ResourceManager.GetString("menubar_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        internal static string menubar_system {
            get {
                return ResourceManager.GetString("menubar_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Werkzeuge ähnelt.
        /// </summary>
        internal static string menubar_tools {
            get {
                return ResourceManager.GetString("menubar_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Flugzeit des Tickets stimmt nicht mit der des Feldes überein. ähnelt.
        /// </summary>
        internal static string message_length_mismatch {
            get {
                return ResourceManager.GetString("message_length_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das ausgewählte Feld kann die Kapazität dieses Blocks nicht tragen. ähnelt.
        /// </summary>
        internal static string message_too_much_weight {
            get {
                return ResourceManager.GetString("message_too_much_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es kann kein für die Flugeigenschaften passender Zeitabschnitt gefunden werden. ähnelt.
        /// </summary>
        internal static string missing_slots_warning {
            get {
                return ResourceManager.GetString("missing_slots_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung: ähnelt.
        /// </summary>
        internal static string name_doubledot {
            get {
                return ResourceManager.GetString("name_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Konfiguration ähnelt.
        /// </summary>
        internal static string new_config {
            get {
                return ResourceManager.GetString("new_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name der neuen Konfiguration: ähnelt.
        /// </summary>
        internal static string new_config_name {
            get {
                return ResourceManager.GetString("new_config_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Datenbank ähnelt.
        /// </summary>
        internal static string new_db {
            get {
                return ResourceManager.GetString("new_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name der neuen Datenbank: ähnelt.
        /// </summary>
        internal static string new_db_name {
            get {
                return ResourceManager.GetString("new_db_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuen Flug erstellen... ähnelt.
        /// </summary>
        internal static string newflt {
            get {
                return ResourceManager.GetString("newflt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll automatisch ein neuer Flug für das angegebene Ziel angelegt werden? ähnelt.
        /// </summary>
        internal static string newflt_warning {
            get {
                return ResourceManager.GetString("newflt_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu... ähnelt.
        /// </summary>
        internal static string newobj {
            get {
                return ResourceManager.GetString("newobj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Profil ähnelt.
        /// </summary>
        internal static string newprofile {
            get {
                return ResourceManager.GetString("newprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tageszeit ähnelt.
        /// </summary>
        internal static string night {
            get {
                return ResourceManager.GetString("night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll dieses Ticket/dieses Ziel wirklich verschoben werden? ähnelt.
        /// </summary>
        internal static string nodemove_question_sub {
            get {
                return ResourceManager.GetString("nodemove_question_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigung ähnelt.
        /// </summary>
        internal static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigen ähnelt.
        /// </summary>
        internal static string notify {
            get {
                return ResourceManager.GetString("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OGN Adresse ähnelt.
        /// </summary>
        internal static string ogn_address {
            get {
                return ResourceManager.GetString("ogn_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OGN-Adresse: ähnelt.
        /// </summary>
        internal static string ogn_doubledot {
            get {
                return ResourceManager.GetString("ogn_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manuell ähnelt.
        /// </summary>
        internal static string ogn_linkmanual {
            get {
                return ResourceManager.GetString("ogn_linkmanual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbleibende ähnelt.
        /// </summary>
        internal static string ogn_linkremain {
            get {
                return ResourceManager.GetString("ogn_linkremain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fallblattanzeige öffnen ähnelt.
        /// </summary>
        internal static string open_flipit {
            get {
                return ResourceManager.GetString("open_flipit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überlappung ähnelt.
        /// </summary>
        internal static string overlap {
            get {
                return ResourceManager.GetString("overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die überlappen. Falls dies nicht gewollt ist, sollten die betroffenen Slots verschoben oder gelöscht werden. ähnelt.
        /// </summary>
        internal static string overlap_warning {
            get {
                return ResourceManager.GetString("overlap_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überladung ähnelt.
        /// </summary>
        internal static string overload {
            get {
                return ResourceManager.GetString("overload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einfügen ähnelt.
        /// </summary>
        internal static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preiskategorie ähnelt.
        /// </summary>
        internal static string price_create {
            get {
                return ResourceManager.GetString("price_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preis: ähnelt.
        /// </summary>
        internal static string price_doubledot {
            get {
                return ResourceManager.GetString("price_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtpreis in € ähnelt.
        /// </summary>
        internal static string price_sum {
            get {
                return ResourceManager.GetString("price_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preiskategorien ähnelt.
        /// </summary>
        internal static string pricecats {
            get {
                return ResourceManager.GetString("pricecats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preis Konfig. ähnelt.
        /// </summary>
        internal static string pricecustomizer {
            get {
                return ResourceManager.GetString("pricecustomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trotzdem Fortfahren ähnelt.
        /// </summary>
        internal static string proceed_anyway {
            get {
                return ResourceManager.GetString("proceed_anyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profil wählen ähnelt.
        /// </summary>
        internal static string profile_choose {
            get {
                return ResourceManager.GetString("profile_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profileditor öffnen... ähnelt.
        /// </summary>
        internal static string profile_editor {
            get {
                return ResourceManager.GetString("profile_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profilverzeichnis ähnelt.
        /// </summary>
        internal static string profile_manager {
            get {
                return ResourceManager.GetString("profile_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Profil ist jetzt bereit.
        ///Falls ihr Profil nicht sofort erscheint, drücken Sie einfach den &quot;Aktualisieren&quot; Knopf. ähnelt.
        /// </summary>
        internal static string profile_ready {
            get {
                return ResourceManager.GetString("profile_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen oder erstellen Sie ein Profil: ähnelt.
        /// </summary>
        internal static string profile_select {
            get {
                return ResourceManager.GetString("profile_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederholen ähnelt.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als NEXUS Slave fortfahren ähnelt.
        /// </summary>
        internal static string remote_continue {
            get {
                return ResourceManager.GetString("remote_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aus anderem Profil importieren ähnelt.
        /// </summary>
        internal static string requestfromdb {
            get {
                return ResourceManager.GetString("requestfromdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu starten ähnelt.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern unter... ähnelt.
        /// </summary>
        internal static string saveas {
            get {
                return ResourceManager.GetString("saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherheit ähnelt.
        /// </summary>
        internal static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flug auswählen ähnelt.
        /// </summary>
        internal static string select_flight {
            get {
                return ResourceManager.GetString("select_flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Sitzung wurde aus Sicherheitsgründen gesperrt. Diese Meldung verschwindet automatisch, wenn die Sperrung aufgehoben ist und der Safe-Mode verlassen wird. ähnelt.
        /// </summary>
        internal static string session_locked {
            get {
                return ResourceManager.GetString("session_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sitzung gesperrt ähnelt.
        /// </summary>
        internal static string session_locked_title {
            get {
                return ResourceManager.GetString("session_locked_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansehen ähnelt.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slot Konfiguration ähnelt.
        /// </summary>
        internal static string slotcustomizer {
            get {
                return ResourceManager.GetString("slotcustomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitfenster ähnelt.
        /// </summary>
        internal static string slots {
            get {
                return ResourceManager.GetString("slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginnen ähnelt.
        /// </summary>
        internal static string startButton {
            get {
                return ResourceManager.GetString("startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgelaufene Flüge beenden ähnelt.
        /// </summary>
        internal static string status_finish_old {
            get {
                return ResourceManager.GetString("status_finish_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Flüge aktualisieren ähnelt.
        /// </summary>
        internal static string status_refresh_all {
            get {
                return ResourceManager.GetString("status_refresh_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuellen Slot aktualisieren ähnelt.
        /// </summary>
        internal static string status_refresh_current {
            get {
                return ResourceManager.GetString("status_refresh_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächsten Slot aktualisieren ähnelt.
        /// </summary>
        internal static string status_refresh_next {
            get {
                return ResourceManager.GetString("status_refresh_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Systemuhr ähnelt.
        /// </summary>
        internal static string systemclock {
            get {
                return ResourceManager.GetString("systemclock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geplante Ereignisse löschen ähnelt.
        /// </summary>
        internal static string systemclock_clear {
            get {
                return ResourceManager.GetString("systemclock_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ticket/Ziel Optionen ähnelt.
        /// </summary>
        internal static string target_option {
            get {
                return ResourceManager.GetString("target_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block Konfig. ähnelt.
        /// </summary>
        internal static string targetcustomizer {
            get {
                return ResourceManager.GetString("targetcustomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tickets ähnelt.
        /// </summary>
        internal static string targets {
            get {
                return ResourceManager.GetString("targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verkaufte Tickets ähnelt.
        /// </summary>
        internal static string targets_sold {
            get {
                return ResourceManager.GetString("targets_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tickets transportiert ähnelt.
        /// </summary>
        internal static string targets_transported {
            get {
                return ResourceManager.GetString("targets_transported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Ziel/Das Ticket ist jetzt fällig. ähnelt.
        /// </summary>
        internal static string ticket_notification {
            get {
                return ResourceManager.GetString("ticket_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeit ähnelt.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  befindet sich außerhalb des Dämmerungsbereichs. Dieser Flug darf möglicherweise nicht legal stattfinden ähnelt.
        /// </summary>
        internal static string too_late {
            get {
                return ResourceManager.GetString("too_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierte Transaktionen ähnelt.
        /// </summary>
        internal static string total_transactions {
            get {
                return ResourceManager.GetString("total_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auslösen ähnelt.
        /// </summary>
        internal static string trigger {
            get {
                return ResourceManager.GetString("trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtumsatz in € ähnelt.
        /// </summary>
        internal static string turnover {
            get {
                return ResourceManager.GetString("turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Muster ähnelt.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Muster: ähnelt.
        /// </summary>
        internal static string type_doubledot {
            get {
                return ResourceManager.GetString("type_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht erlaubte Zeichen wurden aus der Anfrage entfernt ähnelt.
        /// </summary>
        internal static string unallowed_chars_removed {
            get {
                return ResourceManager.GetString("unallowed_chars_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unverändert ähnelt.
        /// </summary>
        internal static string unchanged {
            get {
                return ResourceManager.GetString("unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückgängig ähnelt.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden nicht verknüpfte Tickets in der Datenbank gefunden. Sollen diese neu verknüpft werden? ähnelt.
        /// </summary>
        internal static string unlinked_tgts {
            get {
                return ResourceManager.GetString("unlinked_tgts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank ansehen ähnelt.
        /// </summary>
        internal static string view_db {
            get {
                return ResourceManager.GetString("view_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnung ähnelt.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verfügbare Sitze: ähnelt.
        /// </summary>
        internal static string weight_doubledot {
            get {
                return ResourceManager.GetString("weight_doubledot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passagiere transportiert ähnelt.
        /// </summary>
        internal static string weight_transported {
            get {
                return ResourceManager.GetString("weight_transported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen im 
        ///XFly Manager Studio 2026! ähnelt.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuerst müssen wir eine Konfiguration erstellen, damit das Programm einsatzfähig ist. Der intelligente Assistent wird Ihnen dabei helfen ähnelt.
        /// </summary>
        internal static string welcome_init {
            get {
                return ResourceManager.GetString("welcome_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Instanzen beenden ähnelt.
        /// </summary>
        internal static string xboard_close_all {
            get {
                return ResourceManager.GetString("xboard_close_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luftfahrzeugbericht exportieren... ähnelt.
        /// </summary>
        internal static string xml_report_ac {
            get {
                return ResourceManager.GetString("xml_report_ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ticketbericht exportieren... ähnelt.
        /// </summary>
        internal static string xml_report_target {
            get {
                return ResourceManager.GetString("xml_report_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML-Register ähnelt.
        /// </summary>
        internal static string xmlreport {
            get {
                return ResourceManager.GetString("xmlreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interaktives Register ähnelt.
        /// </summary>
        internal static string xplan {
            get {
                return ResourceManager.GetString("xplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        internal static string xplan_add {
            get {
                return ResourceManager.GetString("xplan_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string xplan_auto {
            get {
                return ResourceManager.GetString("xplan_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anlegen ähnelt.
        /// </summary>
        internal static string xplan_creator {
            get {
                return ResourceManager.GetString("xplan_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        /// </summary>
        internal static string xplan_length {
            get {
                return ResourceManager.GetString("xplan_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung ähnelt.
        /// </summary>
        internal static string xplan_name {
            get {
                return ResourceManager.GetString("xplan_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fixiert ähnelt.
        /// </summary>
        internal static string xplan_persistent {
            get {
                return ResourceManager.GetString("xplan_persistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preis in € ähnelt.
        /// </summary>
        internal static string xplan_price {
            get {
                return ResourceManager.GetString("xplan_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A.S.A.P. ähnelt.
        /// </summary>
        internal static string xplan_quickticket {
            get {
                return ResourceManager.GetString("xplan_quickticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luftfahrzeug ähnelt.
        /// </summary>
        internal static string xplan_select_lfz {
            get {
                return ResourceManager.GetString("xplan_select_lfz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterwegs ähnelt.
        /// </summary>
        internal static string xplan_status_airborne {
            get {
                return ResourceManager.GetString("xplan_status_airborne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelandet ähnelt.
        /// </summary>
        internal static string xplan_status_app {
            get {
                return ResourceManager.GetString("xplan_status_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gestrichen ähnelt.
        /// </summary>
        internal static string xplan_status_cancel {
            get {
                return ResourceManager.GetString("xplan_status_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verspätet ähnelt.
        /// </summary>
        internal static string xplan_status_delayed {
            get {
                return ResourceManager.GetString("xplan_status_delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abflug ähnelt.
        /// </summary>
        internal static string xplan_status_dpt {
            get {
                return ResourceManager.GetString("xplan_status_dpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angekommen ähnelt.
        /// </summary>
        internal static string xplan_status_finished {
            get {
                return ResourceManager.GetString("xplan_status_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tankflug ähnelt.
        /// </summary>
        internal static string xplan_status_fuel {
            get {
                return ResourceManager.GetString("xplan_status_fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Planmäßig ähnelt.
        /// </summary>
        internal static string xplan_status_ontime {
            get {
                return ResourceManager.GetString("xplan_status_ontime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Außer Betrieb ähnelt.
        /// </summary>
        internal static string xplan_status_outofservice {
            get {
                return ResourceManager.GetString("xplan_status_outofservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereit ähnelt.
        /// </summary>
        internal static string xplan_status_ready {
            get {
                return ResourceManager.GetString("xplan_status_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht Verfügbar ähnelt.
        /// </summary>
        internal static string xplan_status_unavail {
            get {
                return ResourceManager.GetString("xplan_status_unavail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannt ähnelt.
        /// </summary>
        internal static string xplan_status_unclear {
            get {
                return ResourceManager.GetString("xplan_status_unclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warten ähnelt.
        /// </summary>
        internal static string xplan_status_waiting {
            get {
                return ResourceManager.GetString("xplan_status_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sitze ähnelt.
        /// </summary>
        internal static string xplan_weight {
            get {
                return ResourceManager.GetString("xplan_weight", resourceCulture);
            }
        }
    }
}
